In [12]:
from __future__ import print_function
import torch
import numpy as np

In [2]:
x = torch.Tensor(5, 3)
print(x)


1.00000e-09 *
  0.0000  0.0000  6.3301
  0.0000  7.8356  0.0000
  0.0000  0.0000  0.0000
  0.0000  7.8399  0.0000
  0.0000  0.0000  0.0000
[torch.FloatTensor of size 5x3]



In [4]:
print(x.size())
# torch.Size is a tuple

torch.Size([5, 3])


In [5]:
y = torch.rand(5, 3)
print(x+y) #1
print(torch.add(x, y)) #2


 0.1408  0.1027  0.6020
 0.5876  0.2126  0.1793
 0.6413  0.4183  0.3897
 0.3013  0.8555  0.5786
 0.3092  0.9505  0.9877
[torch.FloatTensor of size 5x3]


 0.1408  0.1027  0.6020
 0.5876  0.2126  0.1793
 0.6413  0.4183  0.3897
 0.3013  0.8555  0.5786
 0.3092  0.9505  0.9877
[torch.FloatTensor of size 5x3]



In [6]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)


 0.1408  0.1027  0.6020
 0.5876  0.2126  0.1793
 0.6413  0.4183  0.3897
 0.3013  0.8555  0.5786
 0.3092  0.9505  0.9877
[torch.FloatTensor of size 5x3]



In [7]:
# Addition in place
y.add_(x)
print(y)


 0.1408  0.1027  0.6020
 0.5876  0.2126  0.1793
 0.6413  0.4183  0.3897
 0.3013  0.8555  0.5786
 0.3092  0.9505  0.9877
[torch.FloatTensor of size 5x3]



In [8]:
# Any operation that mutates a tensor in-place is post-fixed with an _ 
# For example: x.copy_(y), x.t_(), will change x.

In [9]:
print(x[:, 1])


1.00000e-09 *
  0.0000
  7.8356
  0.0000
  7.8399
  0.0000
[torch.FloatTensor of size 5]



In [10]:
# tensor to numpy
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]

[ 1.  1.  1.  1.  1.]


In [11]:
a.add_(1)
print(a)
print(b)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[ 2.  2.  2.  2.  2.]


In [13]:
# numpy to tensor
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



In [17]:
# CUDA tensors
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    print(x + y)