In [2]:
from __future__ import print_function
import torch
import numpy as np

In [3]:
x = torch.Tensor(5, 3)
print(x)


 0.0000  0.0000  1.7788
 0.0000  1.7789  0.0000
 0.0000  0.0000  0.0000
 0.0000  0.0000  0.0000
 0.0000  0.0000  0.0000
[torch.FloatTensor of size 5x3]



In [4]:
print(x.size())
# torch.Size is a tuple

torch.Size([5, 3])


In [5]:
y = torch.rand(5, 3)
print(x+y) #1
print(torch.add(x, y)) #2


 0.3563  0.6433  2.3216
 0.2285  2.5848  0.1904
 0.4267  0.1398  0.0391
 0.5214  0.3102  0.7697
 0.9610  0.1725  0.4718
[torch.FloatTensor of size 5x3]


 0.3563  0.6433  2.3216
 0.2285  2.5848  0.1904
 0.4267  0.1398  0.0391
 0.5214  0.3102  0.7697
 0.9610  0.1725  0.4718
[torch.FloatTensor of size 5x3]



In [6]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)


 0.3563  0.6433  2.3216
 0.2285  2.5848  0.1904
 0.4267  0.1398  0.0391
 0.5214  0.3102  0.7697
 0.9610  0.1725  0.4718
[torch.FloatTensor of size 5x3]



In [7]:
# Addition in place
y.add_(x)
print(y)


 0.3563  0.6433  2.3216
 0.2285  2.5848  0.1904
 0.4267  0.1398  0.0391
 0.5214  0.3102  0.7697
 0.9610  0.1725  0.4718
[torch.FloatTensor of size 5x3]



Any operation that mutates a tensor in-place is post-fixed with an _ 
For example: x.copy_(y), x.t_(), will change x.

In [8]:
print(x[:, 1])


 0.0000
 1.7789
 0.0000
 0.0000
 0.0000
[torch.FloatTensor of size 5]



In [9]:
# tensor to numpy
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]

[ 1.  1.  1.  1.  1.]


In [10]:
a.add_(1)
print(a)
print(b)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[ 2.  2.  2.  2.  2.]


In [11]:
# numpy to tensor
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



In [12]:
# CUDA tensors for GPU
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    print(x + y)